---
title: "Mobility_behaviour_Decision_Tree_4th_Try"
output: html_document
date: "2025-01-14"
header-includes:
- \setbeamerfont{verbatim}{size=\footnotesize}
---

```{r setup-tree3, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars-tree3, include=FALSE}

library(skimr)
library(dplyr)
library(randomForest)
library(rpart)  # Für den Entscheidungsbaum
library(rpart.plot)  # Für die Visualisierung des Entscheidungsbaums
library(caret)


load("/Users/felixbartke/Desktop/allgreI.RData") 
load("/Users/felixbartke/Desktop/allgreI_with_W.RData")
load("/Users/felixbartke/Desktop/allgreI_filtered.RData")

# Merge allgreI_filtered mit der Spalte age aus allgreI
# Erstelle eine Kopie des Datensatzes
allgreI_filtered_copy <- allgreI_filtered

# Führe die gewünschte Manipulation nur auf der Kopie durch
allgreI_filtered_copy <- merge(allgreI_filtered_copy, 
                               allgreI[, c("id_pers", "age")], 
                               by = "id_pers", 
                               all.x = TRUE)

# Verwende ab hier die Kopie `allgreI_filtered_copy` für weitere Analysen



# Zufällige Teilung von allgreI in Trainings- und Testdaten (70%-30%)
set.seed(123) # Für Reproduzierbarkeit

# Erzeuge zufällige Indizes für die Trainingsdaten von allgreI
train_indices <- sample(1:nrow(allgreI), size = 0.7 * nrow(allgreI))

# Teile allgreI auf
allgreI_filtered_copy_train <- allgreI_filtered_copy[train_indices, ]
allgreI_filtered_copy_test <- allgreI_filtered_copy[-train_indices, ]

# Bestätige die Aufteilung
dim(allgreI_filtered_copy_train) # Zeigt die Dimensionen der Trainingsdaten
dim(allgreI_filtered_copy_test)  # Zeigt die Dimensionen der Testdaten

class(allgreI_filtered_copy_test$immobil)
class(allgreI_filtered_copy_train$immobil)
```


\footnotesize
```{r, echo=FALSE}
# Tabelle erstellen
table_data <- data.frame(
  `used variables` = c("age_group + dispovp + W", "age + dispo + W", "has_car + OCCU1 + W"),
  Accuracy = c(0.85, 0.90, 0.85),
  Precision = c(0, 0.45, 0),
  Recall = c(NaN, 0.87, NaN),
  `F1-Score` = c(NaN, 0.59, NaN)
)

# Tabelle anzeigen
print(table_data)
```


